[project]
name = "xai-2026"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.2.0",
    "jupyter>=1.1.1",
    "learn>=1.0.0",
    "librosa>=0.11.0",
    "matplotlib>=3.10.9",
    "pandas>=3.0.3",
    "sci-kit>=0.1.0",
]
